id: P01FC92F9
initial_creation_type: input
source_metadata:
  title: Ngawang Samten Lodrö Series
  language: bo
  description: 'Texts by and about Khenchen Ngawang Samten Lodrö (ngag dbang bsam
    gtan blo gros, 1868–1931):'
  volume:
    9c1661ebc0e34a0bbe88922644bdd1cf:
      title: 'The Radiant Treasure of Blessings: A Guru Yoga of the Great Vajradhara
        Ngawang Samten Lodrö'
      parent: Guru Yoga
    3f006c1aad3d4230bf1d4d0cf488a707:
      title: 'The Swift Infusion of Blessings: A Lament and Prayer to Invoke the Wisdom
        Mind of Khenchen Vāgindra on the Occasion of His Passing into the Great Peace
        of the Dharmadhātu'
      parent: Prayers
created_at: '2022-03-01T00:59:41.511970'
last_modified_at: '2022-03-01T00:59:41.511972'
statistics:
  total_words: 957
  total_non_words: 94
quality:
  non_words_ratio: 0.1
